apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox
          image: prom/blackbox-exporter:v0.23.0
          args:
            - "--config.file=/etc/blackbox-exporter/blackbox.yml"
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: blackbox-exporter-config
              mountPath: /etc/blackbox-exporter
          resources: 
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: blackbox-exporter-config
          configMap:
            name: blackbox-exporter-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
  namespace: monitoring 
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: blackbox-exporter
      port: 9115
      targetPort: 9115
  type: ClusterIP