apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.43.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config 
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: targets-config
              mountPath: /etc/prometheus/targets.yml
              subPath: targets.yml
            - name: rules-config
              mountPath: /etc/prometheus/rules
          resources: 
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-configmap
      - name: targets-config
        configMap:
          name: targets-configmap
      - name: rules-config
        configMap:
          name: rules-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
  type: ClusterIP
