apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-configmap
  namespace: monitoring
data:
  datasources.yml: |
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        isDefault: true
        jsonData:
            graphiteVersion: "1.1"
            tlsAuth: false
            tlsAuthWithCACert: false
        version: 1
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-configmap
  namespace: monitoring
data:
  dashboards.yml: |
    apiVersion: 1

    providers:
    - name: 'dashboards'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
