apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.4.7
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards-website-monitoring
              mountPath: /var/lib/grafana/dashboards/website-monitoring.json
              subPath: website-monitoring.json
          resources: 
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-configmap
        - name: grafana-datasources
          configMap:
            name: grafana-datasources-configmap
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards-configmap
        - name: grafana-dashboards-website-monitoring
          configMap: 
            name: grafana-dashboard-website-json
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000